The import was failing because this needs to be an Integer
Error in question:
django.contrib.gis.utils.layermapping.LayerMapError: OGR field "<class 'django.contrib.gis.gdal.field.OFTString'>" (of type OFTString) cannot be mapped to Django FloatField.

Example of the mapping allowed values (from: http://phairs-devel.unm.edu/DREAM_DAILY_STAT_SERVER/epht_enviro_virtualenv/lib/python2.6/site-packages/django/contrib/gis/utils/layermapping.py):
        models.IntegerField : (OFTInteger, OFTReal, OFTString),